import {Assets} from 'react-native-ui-lib';

Assets.loadAssetsGroup('icons', {
  ic_eye: require('../assets/icons/ic_eye.png'),
  ic_eye_hide: require('../assets/icons/ic_eye_hide.png'),
  ic_cancel: require('../assets/icons/cancel.png'),
  ic_logout: require('../assets/icons/ic_logout.png'),
  ic_add: require('../assets/icons/ic_add.png'),
  ic_back: require('../assets/icons/ic_back.png'),
  ic_edit: require('../assets/icons/ic_edit.png'),
  ic_github: require('../assets/icons/ic_github.png'),
  ic_camera: require('../assets/icons/ic_camera.png'),
  ic_gallery: require('../assets/icons/ic_gallery.png'),
  ic_setting: require('../assets/icons/ic_setting.png'),
  ic_camera_rotate: require('../assets/icons/ic_camera_rotate.png'),
  ic_flash: require('../assets/icons/ic_flash.png'),
  ic_flash_off: require('../assets/icons/ic_flash_off.png'),
  ic_save: require('../assets/icons/ic_save.png'),
  ic_check: require('../assets/icons/ic_check.png'),
  ic_group: require('../assets/icons/ic_group.png'),
  ic_menu: require('../assets/icons/ic_menu.png'),
  ic_facebook: require('../assets/icons/ic_facebook.png'),
  ic_copy: require('../assets/icons/ic_copy.png'),
  add_emoji: require('../assets/icons/add_emoji.png'),
  ic_send: require('../assets/icons/ic_send.png'),
  ic_next: require('../assets/icons/ic_next.png'),
  ic_message: require('../assets/icons/ic_message.png'),
});
