export type UpdateInfoType =
  | 'CHECKING_FOR_UPDATE'
  | 'UPDATE_AVAILABLE'
  | 'DOWNLOADING_PACKAGE'
  | 'INSTALLING_UPDATE'
  | 'UP_TO_DATE'
  | 'UPDATE_INSTALLED'
  | 'ERROR'
  | 'CHECK_UPDATE'
  | 'APK_UPDATE_AVAILABLE';
